In [1]:
help(sorted)

Help on built-in function sorted in module builtins:

sorted(iterable, /, *, key=None, reverse=False)
    Return a new list containing all items from the iterable in ascending order.
    
    A custom key function can be supplied to customize the sort order, and the
    reverse flag can be set to request the result in descending order.



In [3]:
l = ["A 21", "C 22", "D 12", "A 31"]

sorted(l)

['A 21', 'A 31', 'C 22', 'D 12']

In [6]:
sorted(l, key = lambda x: x.split()[-1])

['D 12', 'A 21', 'C 22', 'A 31']

In [7]:
sort_key = lambda x: x.split()[-1]
sorted(l, key = sort_key)

['D 12', 'A 21', 'C 22', 'A 31']

In [12]:
import random as rnd 

dices = [rnd.randint(1,6) for _ in range(10)]
dices

[6, 5, 3, 4, 5, 2, 5, 4, 5, 6]

In [13]:
import numpy as np 

x = np.random.randint(1,7,10)
x

array([5, 1, 4, 2, 2, 3, 3, 4, 6, 2])

In [14]:
x**2

array([25,  1, 16,  4,  4,  9,  9, 16, 36,  4])

In [23]:
dice1 = np.arange(1, 7)
dice2 = np.arange(1, 7)
dice1.shape = (6,1)


dice1+dice2

array([[ 2,  3,  4,  5,  6,  7],
       [ 3,  4,  5,  6,  7,  8],
       [ 4,  5,  6,  7,  8,  9],
       [ 5,  6,  7,  8,  9, 10],
       [ 6,  7,  8,  9, 10, 11],
       [ 7,  8,  9, 10, 11, 12]])

In [19]:
dice1

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [22]:
dice2.transpose()

array([1, 2, 3, 4, 5, 6])

In [27]:
dice1 = np.arange(1, 7).reshape(6,-1)
dice1 

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [29]:
np.ones(7),np.arange(1,8)

array([1, 2, 3, 4, 5, 6, 7])

In [31]:
p = input("Write two numbers separate with ,")
p = [float(number) for number in p.split(",")]
p


[4.0, 5.0]